### ISSUE TITLE
FR10. Display song/artist title

### ISSUE THREAD

**Issue by srazzaq01** [WSU-4110/JamFynDer#11]
|Requirement_ID FR10. Display song/artist title|
|---|
|**Goal**: Display the name of the song as well as the title as it plays the song
**Stakeholders:** Rafi/users|
| **Description:** When the song starts playing, along with the album cover we also want to display the name and the artist. The information should be displayed in a neat and clear way so that the user is not confused. The system will be able to accurately display the information to the use. |
| **Origin:** Our initial meeting we decided that displaying the basic information about the song such as the artist and title would be necessary |
| **Version:** 1.0|  
|**Date:**  9/18/22  
|  Priority: 3 |

**Comment by miketocco** [comment]
Implemented via player api
