### ISSUE TITLE
FR11. Log Out

### ISSUE THREAD

**Issue by AliJanbeih** [WSU-4110/JamFynDer#12]
|Requirement_ID 11 Log Out|
|---|
|**Goal**: Display a log out icon for the users to log out of their Spotify account.
**Stakeholders:** Rafi/users|
| **Description:** When the user decides to exit out of their application, they will have the option to log out of their account for obvious privacy and security reasons. The log out icon will be displayed on the top right corner of the application. |
| **Origin:** Our initial meeting we thought it was necessary that the user needs to be provided with the log out function. |
| **Version:** 1.0|  
|**Date:**  9/18/22  
|  Priority: 2 |

**Comment by Urban-Programmer** [comment]
Feature is completed by express server branch
Switching integration to main branch
No action warranted
