### ISSUE TITLE
FR12. Display playback Interface

### ISSUE THREAD

**Issue by Urban-Programmer** [WSU-4110/JamFynDer#13]
|Requirement_ID FR.12 Display playback interface|
|---|
|**Goal**: Display the name of the song as well as the title as it plays the song
**Stakeholders:** Users|
| **Description:** When the song is playing, it should display a bar measuring the time from the beginning from the song till the end. It should be represented by a smooth UI, that will give a user a precise measure to tell where the song is at the certain point. |
| **Origin:** From our first meeting we discussed the importance of a having a short sample of the music, and how we should provide the user with a interactive UI |
| **Version:** 1.0|  
|**Date:**  9/18/22  
|  Priority: 3 |

**Comment by miketocco** [comment]
Implemented
