### ISSUE TITLE
FR13. User Unique ID

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#14]
|FR13.  Unique ID|
|---|
|**Goal**: This feature will give a unique ID to users to increase security.
**Stakeholders:** All users|
| **Description:**When a new user creates an account, they will be provided with a unique ID which will be only seen to the user, and be used to protect identification and authorization. |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 1 |

**Comment by Urban-Programmer** [comment]
Retiring this due to the generated Spotify Login Creds from the API. No need to redundantly create a new user ID
