### ISSUE TITLE
FR15. Profile Settings

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#16]
|FR15.  Setting|
|---|
|**Goal**: The app will have a settings tab which will let the user delete their account and logout.
**Stakeholders:** All users|
| **Description:** Each user will have a settings tab that will allow the user to delete their account if they choose to do so for any reason, and allow the user to logout of their account. |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 3 |

**Comment by Urban-Programmer** [comment]
Few Changes, we no longer will create an additional account linked to their Spotify. We will manipulate the data provided by Spotify to generate a recommended song.
