### ISSUE TITLE
FR1. Video Tutorial 

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#2]
|FR1.  Video Tutorial|
|---|
|**Goal**: This feature will help new users traverse through our web application and show them what each feature does.
**Stakeholders:** All users|
| **Description:** When a new user logs in to our web application, they may not know where to start, so we have decided to create a button that will send the user to the linked video tutorial and teach them all about the app and what each button does. |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 4 |

**Comment by Urban-Programmer** [comment]
No longer apart of our roll-out plan
