### ISSUE TITLE
NFR19. Portability

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#20]
|NFR19.  Portability|
|---|
|**Goal**: Our app should be available on any device since it is a web application.
**Stakeholders:** All users|
| **Description:** Since our app is a web app, any user can access it via mobile devices, laptops, desktops, etc. |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022

**Comment by Urban-Programmer** [comment]
Website is hosted on a web server, and can be hosted on a mobile device, laptop and/or desktop
