### ISSUE TITLE
FR2. Begin Music Search

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#3]
|FR2.  Begin Music Search|
|---|
|**Goal**: This feature is a button that appears after the login and tutorial video that brings you to the homepage of the application.
**Stakeholders:** All users|
| **Description:** Each time a new user enters into the app with their username and password, they are prompt with an optional tutorial video, but after the video, the user will be welcome to the homepage with a button that will say "Begin Music Search". |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 4 |

**Comment by miketocco** [comment]
Implement
