### ISSUE TITLE
FR3. Display Album Artwork

### ISSUE THREAD

**Issue by Jae72** [WSU-4110/JamFynDer#4]
|FR3.  Display Album Artwork|
|---|
|**Goal**: This feature will be on the homepage of our app and will display the album artwork.
**Stakeholders:** All users|
| **Description:** This feature will display the album artwork in the middle of the like and dislike button. |
| **Origin:** This feature was discussed in our first meeting for the applications specifications.|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 3 |

**Comment by miketocco** [comment]
Implemented via player api
