### ISSUE TITLE
FR6. Playlist Generation 

### ISSUE THREAD

**Issue by hwinczner** [WSU-4110/JamFynDer#7]
|FR6 Playlist Generation|
|---|
|**Goal**: To create a playlist for the user based on the liked songs|
**Stakeholders:** Rafi Sultan, users|
| **Description:** After a user clicks like while listening to a song, the songs URI will be stored within a playlist under there Spotify account. if this is a first time user, a playlist will be generated and this song will be the first within said generated playlist. After liking a certain genre, more music of that genre will be played, giving the user the ability to expand their playlist. If the user clicks the dislike button the priority of said genre will decrease, and the song will go into a repository of disliked songs. Which the user can view and go through, incase they liked a song they accidently disliked.|
| **Origin:** N/A|
| **Version:** 1.0|  
|**Date:** 9/18/22|  
|  **Priority:** 1 |

**Comment by miketocco** [comment]
Implemented
