### ISSUE TITLE
FR7. Resetting a users likes or dislikes 

### ISSUE THREAD

**Issue by hwinczner** [WSU-4110/JamFynDer#8]
|FR7 Reset Button|
|---|
|**Goal**: to give the users the ability to reset there like and dislike history |
**Stakeholders:** Rafi Sultan, users|
| **Description:** Once the users have built up a history of likes and dislikes, the user has the ability to reset or delete their history. this just gives the user more freedom if they want to listen to a new genre of songs, and are dissatisfied with the current selection they are listening to. Resetting there history will generate a new playlist, erasing any previous genre priority that the user had.|
| **Origin:** N/A|
| **Version:** 1.0|  
|**Date:** 9/18/22| 
|  **Priority:** 4|

**Comment by miketocco** [comment]
not implemented, handled upon logout
